version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/1.23"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "main"
    ignore:
      - dependency-name: "golang"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "docker"
    directory: "/1.24"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "main"
    ignore:
      - dependency-name: "golang"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "docker"
    directory: "/1.25"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "main"
    ignore:
      - dependency-name: "golang"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
